spring:
  application:
    name: Ordermanagment

  datasource:
    url: jdbc:postgresql://localhost:5432/Ordermanage
    username: postgres
    password: Gopal
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
